# Generated by Django 3.2.16 on 2024-02-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='activity',
            field=models.TextField(default=''),
        ),
    ]
