# Generated by Django 3.2.16 on 2024-02-19 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_history_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
