# Generated by Django 3.2.16 on 2024-02-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20240219_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'permissions': (('download_Note', 'Can Download Notes'),)},
        ),
    ]
